init: Checkpoint in implementing l4start()
This is a checkpoint commit. I was able to weed out a lot of quirks
from header files and implemented a shit-load of functions.

There are a lot of comments of the following forms all around the
code:

  /* TODO <foo> */
  /* XXX cl: <bar> */

to indicate missing bits (TODO) or wrong implementations for the sake
of not driving me mad (XXX cl). Next to these things, the main.c DOES
NOT COMPILE at the moment.

cc1: warnings being treated as errors
sys/arch/i386/l4/main.c: In function 'l4x_handle_pagefault':
sys/arch/i386/l4/main.c:580: warning: implicit declaration of function 'l4x_forward_pf'
sys/arch/i386/l4/main.c: In function 'l4x_setup_die_utcb':
sys/arch/i386/l4/main.c:585: error: storage size of 'regs' isn't known
sys/arch/i386/l4/main.c:594: warning: implicit declaration of function 'utcb_exc_to_ptregs'
sys/arch/i386/l4/main.c:601: error: invalid application of 'sizeof' to incomplete type 'struct pt_regs'
sys/arch/i386/l4/main.c:602: error: dereferencing pointer to incomplete type
sys/arch/i386/l4/main.c:585: warning: unused variable 'regs'
*** Error code 1